/**
 * Shape Texture Builder - Generates MSDF and Alpha textures from source.svg files
 *
 * This tool processes source.svg files in public/shapes/{shapeName}/ and generates:
 * - msdf.png: MSDF texture for sharp edge rendering (via msdfgen)
 * - alpha.png: Grayscale alpha texture for intensity modulation (via sharp)
 *
 * Pipeline:
 * 1. Read source.svg (generated by generateShapeSources.ts)
 * 2. Extract <g id="msdf"> -> msdf-mask.svg -> msdf.png (via msdfgen)
 * 3. Extract <g id="alpha"> -> alpha-grads.svg -> alpha.png (via sharp)
 * 4. Update metadata.json with shape info
 *
 * Prerequisites:
 *   - msdfgen must be installed (run .devcontainer/setup-msdfgen.sh)
 *   - sharp must be installed (npm install sharp)
 *
 * Usage:
 *   npx tsx src/tools/buildShapeTextures.ts
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SHAPES_DIR = path.join(__dirname, '../public/shapes');

// MSDF generation parameters
const PX_RANGE = 8.0;

// ============================================================
// SVG Parsing
// ============================================================

/**
 * Extract viewBox dimensions from SVG
 */
function extractViewBox(svgContent: string): { width: number; height: number } | null {
  const viewBoxMatch = svgContent.match(/viewBox=["']([^"']+)["']/);
  if (viewBoxMatch) {
    const parts = viewBoxMatch[1].split(/\s+/).map(Number);
    if (parts.length >= 4) {
      return { width: parts[2], height: parts[3] };
    }
  }
  return null;
}

/**
 * Extract <defs> content from SVG
 */
function extractDefs(svgContent: string): string {
  const defsMatch = svgContent.match(/<defs[^>]*>([\s\S]*?)<\/defs>/i);
  return defsMatch ? defsMatch[1] : '';
}

/**
 * Extract content of a group by ID
 */
function extractGroupContent(svgContent: string, groupId: string): string | null {
  // Match <g id="groupId">...</g> including content
  const regex = new RegExp(`<g[^>]*id=["']${groupId}["'][^>]*>([\\s\\S]*?)</g>`, 'i');
  const match = svgContent.match(regex);
  if (match) {
    return match[1].trim();
  }
  return null;
}

/**
 * Check if group content has actual drawable elements (not just comments)
 */
function hasDrawableContent(content: string | null): boolean {
  if (!content) return false;
  // Remove comments and check for actual elements
  const withoutComments = content.replace(/<!--[\s\S]*?-->/g, '').trim();
  return (
    withoutComments.length > 0 && /<(path|rect|circle|ellipse|polygon|line)/i.test(withoutComments)
  );
}

/**
 * Find gradient IDs used in content (url(#id) references)
 */
function findUsedGradientIds(content: string): string[] {
  const matches = content.matchAll(/url\(#([^)]+)\)/g);
  return [...new Set([...matches].map((m) => m[1]))];
}

/**
 * Extract specific gradient definitions by ID
 */
function extractGradientDefs(defsContent: string, ids: string[]): string {
  const gradients: string[] = [];

  for (const id of ids) {
    const linearMatch = defsContent.match(
      new RegExp(`<linearGradient[^>]*id=["']${id}["'][^>]*>[\\s\\S]*?</linearGradient>`, 'i')
    );
    const radialMatch = defsContent.match(
      new RegExp(`<radialGradient[^>]*id=["']${id}["'][^>]*>[\\s\\S]*?</radialGradient>`, 'i')
    );

    if (linearMatch) gradients.push(linearMatch[0]);
    if (radialMatch) gradients.push(radialMatch[0]);
  }

  return gradients.join('\n    ');
}

/**
 * Convert SVG shapes to path data for MSDF compatibility
 * Merges circles, rectangles, and paths into a single path with subpaths
 */
function convertShapesToPath(content: string): string {
  const pathParts: string[] = [];

  // Extract existing path d attributes
  const pathMatches = content.matchAll(/<path[^>]*d=["']([^"']+)["'][^>]*\/?>/gi);
  for (const match of pathMatches) {
    pathParts.push(match[1]);
  }

  // Convert circles to path
  const circleMatches = content.matchAll(
    /<circle[^>]*cx=["']([^"']+)["'][^>]*cy=["']([^"']+)["'][^>]*r=["']([^"']+)["'][^>]*\/?>/gi
  );
  for (const match of circleMatches) {
    const cx = Number.parseFloat(match[1]);
    const cy = Number.parseFloat(match[2]);
    const r = Number.parseFloat(match[3]);
    pathParts.push(
      `M ${cx - r} ${cy} A ${r} ${r} 0 1 0 ${cx + r} ${cy} A ${r} ${r} 0 1 0 ${cx - r} ${cy} Z`
    );
  }

  // Convert rectangles to path
  const rectMatches = content.matchAll(
    /<rect[^>]*(?:x=["']([^"']*)["'])?[^>]*(?:y=["']([^"']*)["'])?[^>]*width=["']([^"']+)["'][^>]*height=["']([^"']+)["'][^>]*\/?>/gi
  );
  for (const match of rectMatches) {
    const x = Number.parseFloat(match[1] || '0');
    const y = Number.parseFloat(match[2] || '0');
    const w = Number.parseFloat(match[3]);
    const h = Number.parseFloat(match[4]);
    pathParts.push(`M ${x} ${y} L ${x + w} ${y} L ${x + w} ${y + h} L ${x} ${y + h} Z`);
  }

  return pathParts.join(' ');
}

// ============================================================
// Generation Functions
// ============================================================

/**
 * Check if msdfgen is installed
 */
function checkMsdfgen(): boolean {
  try {
    execSync('msdfgen --version', { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if sharp is available for alpha rendering
 */
async function checkSharp(): Promise<boolean> {
  try {
    await import('sharp');
    return true;
  } catch {
    return false;
  }
}

/**
 * Generate MSDF from SVG using msdfgen CLI
 */
function generateMsdfPng(
  svgPath: string,
  outputPath: string,
  width: number,
  height: number
): boolean {
  if (!fs.existsSync(svgPath)) {
    return false;
  }

  const cmd = [
    'msdfgen',
    'msdf',
    '-svg',
    svgPath,
    '-o',
    outputPath,
    '-size',
    width.toString(),
    height.toString(),
    '-pxrange',
    PX_RANGE.toString(),
    '-autoframe',
  ].join(' ');

  try {
    execSync(cmd, { stdio: 'pipe' });
    return true;
  } catch (error: unknown) {
    const err = error as { stderr?: Buffer };
    console.error(`    Failed: ${err.stderr?.toString() || 'Unknown error'}`);
    return false;
  }
}

/**
 * Render alpha SVG to grayscale PNG using sharp
 */
async function generateAlphaPng(
  svgPath: string,
  outputPath: string,
  width: number,
  height: number
): Promise<boolean> {
  if (!fs.existsSync(svgPath)) {
    return false;
  }

  try {
    const sharp = (await import('sharp')).default;
    const svgBuffer = fs.readFileSync(svgPath);

    await sharp(svgBuffer).resize(width, height).grayscale().png().toFile(outputPath);

    return true;
  } catch (error) {
    console.error(`    Failed to render alpha: ${error}`);
    return false;
  }
}

/**
 * Process source.svg and extract intermediate SVGs
 */
function processSourceSvg(shapeDir: string): {
  hasMsdf: boolean;
  hasAlpha: boolean;
  width: number;
  height: number;
} {
  const sourcePath = path.join(shapeDir, 'source.svg');

  if (!fs.existsSync(sourcePath)) {
    console.log(`  No source.svg found`);
    return { hasMsdf: false, hasAlpha: false, width: 0, height: 0 };
  }

  const svgContent = fs.readFileSync(sourcePath, 'utf-8');
  const viewBox = extractViewBox(svgContent);
  const defsContent = extractDefs(svgContent);

  if (!viewBox) {
    console.error(`  Error: No viewBox in source.svg`);
    return { hasMsdf: false, hasAlpha: false, width: 0, height: 0 };
  }

  const { width, height } = viewBox;
  const viewBoxAttr = `viewBox="0 0 ${width} ${height}"`;

  let hasMsdf = false;
  let hasAlpha = false;

  // Extract and process MSDF group
  const msdfContent = extractGroupContent(svgContent, 'msdf');
  if (hasDrawableContent(msdfContent)) {
    const pathData = convertShapesToPath(msdfContent!);
    if (pathData) {
      const msdfSvg = `<svg xmlns="http://www.w3.org/2000/svg" ${viewBoxAttr}>
  <path d="${pathData}" fill="black"/>
</svg>
`;
      fs.writeFileSync(path.join(shapeDir, 'msdf-mask.svg'), msdfSvg);
      console.log(`    -> msdf-mask.svg`);
      hasMsdf = true;
    }
  }

  // Extract and process alpha group
  const alphaContent = extractGroupContent(svgContent, 'alpha');
  if (hasDrawableContent(alphaContent)) {
    const usedGradients = findUsedGradientIds(alphaContent!);
    const gradientDefs = extractGradientDefs(defsContent, usedGradients);

    const defsSection = gradientDefs
      ? `
  <defs>
    ${gradientDefs}
  </defs>`
      : '';

    // Add white background for proper alpha rendering (multiply blend needs a base)
    const alphaSvg = `<svg xmlns="http://www.w3.org/2000/svg" ${viewBoxAttr}>${defsSection}
  <rect width="${width}" height="${height}" fill="white"/>
  ${alphaContent}
</svg>
`;
    fs.writeFileSync(path.join(shapeDir, 'alpha-grads.svg'), alphaSvg);
    console.log(`    -> alpha-grads.svg`);
    hasAlpha = true;
  }

  return { hasMsdf, hasAlpha, width, height };
}

/**
 * Process a single shape directory
 */
async function processShape(
  shapeName: string,
  hasMsdfgen: boolean,
  hasSharp: boolean
): Promise<{
  name: string;
  width: number;
  height: number;
  hasMsdf: boolean;
  hasAlpha: boolean;
} | null> {
  const shapeDir = path.join(SHAPES_DIR, shapeName);

  console.log(`Processing: ${shapeName}`);

  // Step 1: Process source.svg to extract intermediate SVGs
  const { hasMsdf: sourceMsdf, hasAlpha: sourceAlpha, width, height } = processSourceSvg(shapeDir);

  if (width === 0 || height === 0) {
    return null;
  }

  let hasMsdf = false;
  let hasAlpha = false;

  // Step 2: Generate msdf.png
  const msdfMaskPath = path.join(shapeDir, 'msdf-mask.svg');
  const msdfPngPath = path.join(shapeDir, 'msdf.png');

  if (sourceMsdf && hasMsdfgen && fs.existsSync(msdfMaskPath)) {
    console.log(`  Generating msdf.png...`);
    if (generateMsdfPng(msdfMaskPath, msdfPngPath, width, height)) {
      console.log(`    -> msdf.png`);
      hasMsdf = true;
    }
  }

  // Step 3: Generate alpha.png
  const alphaGradsPath = path.join(shapeDir, 'alpha-grads.svg');
  const alphaPngPath = path.join(shapeDir, 'alpha.png');

  if (sourceAlpha && hasSharp && fs.existsSync(alphaGradsPath)) {
    console.log(`  Generating alpha.png...`);
    if (await generateAlphaPng(alphaGradsPath, alphaPngPath, width, height)) {
      console.log(`    -> alpha.png`);
      hasAlpha = true;
    }
  }

  return { name: shapeName, width, height, hasMsdf, hasAlpha };
}

// ============================================================
// Main
// ============================================================

async function main(): Promise<void> {
  console.log('Shape Texture Builder\n');
  console.log('Processes source.svg files to generate MSDF and alpha textures.\n');

  // Check prerequisites
  const hasMsdfgen = checkMsdfgen();
  const hasSharp = await checkSharp();

  if (!hasMsdfgen) {
    console.error('Warning: msdfgen is not installed. MSDF generation will be skipped.');
    console.error('Run: .devcontainer/setup-msdfgen.sh\n');
  }

  if (!hasSharp) {
    console.warn('Warning: sharp is not available. Alpha rendering will be skipped.');
    console.warn('Run: npm install sharp\n');
  }

  if (!hasMsdfgen && !hasSharp) {
    console.error('Error: No generation tools available.');
    process.exit(1);
  }

  // Find all shape directories with source.svg
  const entries = fs.readdirSync(SHAPES_DIR, { withFileTypes: true });
  const shapeNames = entries
    .filter((e) => e.isDirectory())
    .filter((e) => fs.existsSync(path.join(SHAPES_DIR, e.name, 'source.svg')))
    .map((e) => e.name);

  if (shapeNames.length === 0) {
    console.log('No shapes found with source.svg files.');
    console.log('Run generateShapeSources.ts first to create source.svg files.');
    process.exit(0);
  }

  console.log(`Found ${shapeNames.length} shapes: ${shapeNames.join(', ')}\n`);

  // Process each shape
  const results: Array<{
    name: string;
    width: number;
    height: number;
    hasMsdf: boolean;
    hasAlpha: boolean;
  }> = [];

  for (const shapeName of shapeNames) {
    const result = await processShape(shapeName, hasMsdfgen, hasSharp);
    if (result) {
      results.push(result);
    }
    console.log('');
  }

  // Write metadata file
  const metadata = {
    pxRange: PX_RANGE,
    shapes: results,
  };

  const metaPath = path.join(SHAPES_DIR, 'metadata.json');
  fs.writeFileSync(metaPath, JSON.stringify(metadata, null, 2));
  console.log(`Metadata: ${metaPath}`);

  console.log('\nDone!');
}

main().catch(console.error);
